config/routes.rb
Rails.application.routes.draw do
  
  resources :appointments

  
  devise_for :users
  
  
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    
    belongs_to :location
    has_many :payment
    
    accepts_nested_attributes_for :payment
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105}, 
    format: { with: VALID_EMAIL_REGEX }
        
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :date_of_birth, presence: true
    validates :gender, presence: true
    validates :phone, presence: true, length: { is: 10 }
    #validate :no_past_date

end

app/models/location.rb
class Location < ApplicationRecord
    has_many :appointments
    
end

app/models/payment.rb
class Payment < ApplicationRecord
    
    attr_accessor :card_number, :card_cvv, :card_expires_month, :card_expires_year
    belongs_to :appointment
    
    def self.month_options
        Date::MONTHNAMES.compact.each_with_index.map { |name, i| ["#{i+1} - #{name}", i+1]}
    end
    
    def self.year_options
        (Date.today.year..(Date.today.year+10)).to_a
    end

    def process_payment
        customer = Stripe::Customer.create email: email, card: token
        Stripe::Charge.create customer: customer.id,
        amount: 1000,
        description: 'COVID PCR Test',
        currency: 'usd'
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :authenticate_user!
    
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

    skip_before_action :authenticate_user!, only: [:new, :create, :confirmation]
    
    def new
        @appointment = Appointment.new
    end
    
    def create
        
        @appointment = Appointment.new(appointment_params)
        if @appointment.save
            name = @appointment.first_name
            appointment_time = @appointment.appointment_time.strftime("%d-%m-%Y at %H:%M").to_s
            location = @appointment.location.name
            flash[:notice] = "Thank you, " + name + "! Your appointment was created successfully for " + appointment_time + ", at " + location + "."
            redirect_to root_path
        else
           render 'new' 
        end
    end 
    
    private
    
    def appointment_params
       params.require(:appointment).permit(:first_name, :last_name, :date_of_birth, :gender, :phone, :email, :appointment_time, :location_id) 
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  skip_before_action :authenticate_user!, only: [:index]
  
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/appointments/new.html.erb
<script language="Javascript">
    Stripe.setPublishableKey("<%= ENV['STRIPE_TEST_PUBLISHABLE_KEY'] %>")
</script>

<div class="justify-content-center">
    <h1 class="text-center"> Book an Appointment </h1>
    
    <%= render 'shared/errors' %>
    
    <div class="col-lg-12 col-md-4 mb-4">
        <%= form_with(model: @appointment, local: true, html: { role: "form", class: 'cc_form'}) do |f| %>
        
            <div class="form-group">
                <%= f.label 'Location' %>
                <%= f.collection_select :location_id, Location.order(:name), :id, :name, style: 'display: block;'%>
            </div>
            <div class="form-group">
                <%= f.label :appointment_time %>
                <div class="col-2">
                    <%= f.datetime_local_field  :appointment_time, class:"form-control shadow rounded", placeholder: "Appointment"  %> 
                </div>
            </div>
            <div class="form-group">
                <%= f.label :first_name %>
                <div class="col-2">
                    <%= f.text_field :first_name, class:"form-control shadow rounded", placeholder: "First name"  %> 
                </div>
            </div>
            <div class="form-group">
                <%= f.label :last_name %>
                <div class="col-2">
                    <%= f.text_field :last_name, class:"form-control shadow rounded", placeholder: "Last name"  %> 
                </div>
            </div>
            <div class="form-group">
                <%= f.label :date_of_birth %>
                <div class="col-2">
                    <%= f.date_field :date_of_birth, class:"form-control shadow rounded", placeholder: ""  %> 
                </div>
            </div>
            <div class="form-group">
                <%= f.label :gender %>
                <div class="col-2">
                    <%= f.radio_button :gender, "Male" %>
                    <%= f.label :gender, "Male" %>
                    <%= f.radio_button :gender, "Female" %>
                    <%= f.label :gender, "Female" %>
                </div>
            </div>
            <div class="form-group">
                <%= f.label :phone %>
                <div class="col-2">
                    <%= f.text_field :phone, class:"form-control shadow rounded", placeholder: "No spaces required"  %> 
                </div>
            </div>
            <div class="form-group">
                <%= f.label :email %>
                <div class="col-2">
                    <%= f.text_field :email, class:"form-control shadow rounded", placeholder: "Example@example.com"  %> 
                </div>
            </div>
            <div class="my-4">
                <hr>
            </div>
            
            <p class="lead">Payment Details</p><br>
            <%= fields_for( :payment ) do |p| %>
                <div class="row col-md-12 mb-2">
                    <div class="form-group col-md-4">
                        <%= p.label :card_number, "Card Number", data: {stripe: 'label'} %>
                        <%= p.text_field :card_number, class: "form-control"%>
                    </div>
                    <div class="form-group col-md-2">
                        <%= p.label :card_cvv, "Card CVV", data: {stripe: 'label'} %>
                        <%= p.text_field :card_cvv, class: "form-control" %>
                    </div>
                    <div class="form-group col-md-6">
                        <div class="col-md-12">
                            <%= p.label :card_expires, "Card Expires", data: {stripe: 'label'} %>
                        </div>
                        <div class="col-md-3">
                            <%= p.select :card_expires_month, options_for_select(Payment.month_options),
                                { include_blank: 'Month' },
                                "data-stripe" => "exp-month",
                                class:"form-control" %>
                        </div>
                        <div class="col-md-3">
                            <%= p.select :card_expires_year, options_for_select(Payment.year_options.push),
                                { include_blank: 'Year' },
                                class:"form-control", 
                                data: {stripe: "exp-year"}%>
                        </div>
                    </div>
                </div>
            <% end %>
           <div class="form-group row text-center">
                <%= f.submit class:"btn blue-button"%>
            </div>
        <% end %>
    </div>
</div>

app/views/home/index.html.erb
<div class="bg-overlay justify-content-center text-center">
	<div class="row text-center">
		<h1>COVID 19 Test Booking</h1></br>
    <p class="lead">Book tests to see your COVID-19 status <br/> or to release for travel.</p>
    <br>
	</div>
	<div class="row justify-content-center text-center">
  	<div class='home-list-bg justify-content-center text-center'>
        <p class="lead blue-icon"><%= fa_icon 'check-circle' %> Accredited Clinic and Laboratory</p>
        <p class="lead blue-icon"><%= fa_icon 'check-circle' %> Certificate Signed by Registered Doctor</p>
        <p class="lead blue-icon"><%= fa_icon 'check-circle' %> Government listed Test Center for Test to Release</p>
        <p class="lead blue-icon"><%= fa_icon 'check-circle' %> Swabs Taken by Trained Clinicians</p>
        <p class="lead blue-icon"><%= fa_icon 'check-circle' %> All Documentation Provided in the Price</p>
           
        <%= link_to 'Book Appointment', new_appointment_path, class:"btn blue-button btn-lg" %>
      </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer" style="width:100%">
  <div class="container">
      <div class="row align-items-center">
        <div class="col" style="text-align:center;float:left;width:auto;display:inline-block;">
          <%= image_tag("HMC-logo.png", width:150) %>
        </div>
        <div class="col" style="text-align:left;margin-left:20rem;width:auto;display:inline-block;color:white;">
            <b><h2>Contact</h2></b>
            <p><%= fa_icon 'phone lg'%> 1 2664 111 1111</p>
            <p><%= fa_icon 'envelope lg'%> info@hmc.com</p>
            <p><%= fa_icon 'map-marker lg'%> South Hill, Anguilla</p><br>
            <a style="color:white;"> Terms & Conditions</a> | <a style="color:white;"> Privacy Policy</a>
            
        </div>
        <div class="col" style="text-align:left;float:right;width:auto;display:inline-block;color:white;">
          <b><h2>About</h2></b>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br>Vivamus pretium finibus purus, a lobortis ante rhoncus in.<br>
          Vestibulum malesuada ex non mattis rutrum. Maecenas tempor ipsum quam,<br> non egestas odio mollis id. Donec interdum diam at erat dictum dignissim.<br>
          Quisque eget tortor nulla.</p><br>
          <p>@ <%= Date.today.year %> Hughes Medical Center. All Rights Reserved</p>
        </div>
      </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-expand-lg navbar-light bg-s">
    <div class="container">
        <%= link_to root_path, class:'navbar-brand' do %> 
                <%= image_tag("HMC-logo.jpg", width: 100, class:'neg-top-margin') %>
                <%= link_to 'Hughes Medical Center', root_path, class: 'navbar-brand brand-text' %>
        <% end %>
       
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "FAQs", "/path4"  %></li>
            <li><%= link_to "Terms & Conditions", "/path2"  %></li>
            <li><%= link_to "Privacy Policy", "/path3"  %></li>
            <li><%= link_to "Contact Us", "/path1", class:'text-dark'  %></li>
          </ul>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title><%= content_for?(:title) ? yield(:title) : "HmcPortal" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

   
    <%= javascript_include_tag "https://js.stripe.com/v2/" %>
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>

    <div id="wrap">
    <div class="container">
        <%= bootstrap_flash %>
          <%= yield %>
    </div>
    <div id="push"></div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if @appointment.errors.any? %>
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">The following errors prevented the appointment from being made: </h4>
        <ul>
            <% @appointment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %><br>